const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.Camera3D,
		C3.Plugins.Audio,
		C3.Plugins.Shape3D,
		C3.Plugins.Text,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Sin.Cnds.ComparePeriod,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{TileMovement: 0},
	{ScrollTo: 0},
	{Tyler: 0},
	{TiledBackground: 0},
	{Void: 0},
	{Keyboard: 0},
	{Solid: 0},
	{InvisbleVoid: 0},
	{brickWall: 0},
	{topOfWall: 0},
	{oKeys: 0},
	{torch: 0},
	{pChest: 0},
	{Gate2: 0},
	{Sine: 0},
	{NKnightsUpdown: 0},
	{Collider1: 0},
	{Sprite2: 0},
	{tylerDeath: 0},
	{table: 0},
	{lostButton: 0},
	{Door: 0},
	{chestCollider: 0},
	{Gate3: 0},
	{Mouse: 0},
	{lChair: 0},
	{Chimney: 0},
	{pChest2: 0},
	{checkpoint: 0},
	{Bullet: 0},
	{king: 0},
	{snowFlow: 0},
	{TiledBackground2: 0},
	{"3DCamera": 0},
	{snow: 0},
	{Audio: 0},
	{princess: 0},
	{Sprite5: 0},
	{Arrows: 0},
	{MetalPipes: 0},
	{brickWall2: 0},
	{topOfWall2: 0},
	{brickWall3: 0},
	{"3DShape": 0},
	{outsideTurret: 0},
	{rBulletKey: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{pChest4: 0},
	{ArrowDestroyer: 0},
	{Gate1: 0},
	{pChest3: 0},
	{Text: 0},
	{bkeys: 0},
	{gKeys: 0},
	{kingText1: 0},
	{standKing: 0},
	{dCollider: 0},
	{Sprite6: 0},
	{Sprite4: 0},
	{next: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Text2: 0},
	{badDeath: 0},
	{Level: 0},
	{checkPoint: 0},
	{rKeys: 0},
	{bKeys: 0}
];

self.InstanceType = {
	Tyler: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Void: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	InvisbleVoid: class extends self.ISpriteInstance {},
	brickWall: class extends self.ITiledBackgroundInstance {},
	topOfWall: class extends self.ISpriteInstance {},
	oKeys: class extends self.ISpriteInstance {},
	torch: class extends self.ISpriteInstance {},
	pChest: class extends self.ISpriteInstance {},
	Gate2: class extends self.ISpriteInstance {},
	NKnightsUpdown: class extends self.ISpriteInstance {},
	Collider1: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	tylerDeath: class extends self.ISpriteInstance {},
	table: class extends self.ISpriteInstance {},
	lostButton: class extends self.ISpriteInstance {},
	Door: class extends self.ISpriteInstance {},
	chestCollider: class extends self.ISpriteInstance {},
	Gate3: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	lChair: class extends self.ISpriteInstance {},
	Chimney: class extends self.ISpriteInstance {},
	pChest2: class extends self.ISpriteInstance {},
	checkpoint: class extends self.ISpriteInstance {},
	king: class extends self.ISpriteInstance {},
	snowFlow: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	_3DCamera: class extends self.IInstance {},
	snow: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	princess: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Arrows: class extends self.ISpriteInstance {},
	MetalPipes: class extends self.ISpriteInstance {},
	brickWall2: class extends self.ITiledBackgroundInstance {},
	topOfWall2: class extends self.ISpriteInstance {},
	brickWall3: class extends self.ITiledBackgroundInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	outsideTurret: class extends self.ISpriteInstance {},
	rBulletKey: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	pChest4: class extends self.ISpriteInstance {},
	ArrowDestroyer: class extends self.ISpriteInstance {},
	Gate1: class extends self.ISpriteInstance {},
	pChest3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	bkeys: class extends self.ISpriteInstance {},
	gKeys: class extends self.ISpriteInstance {},
	kingText1: class extends self.ISpriteInstance {},
	standKing: class extends self.ISpriteInstance {},
	dCollider: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {}
}